### Testar a raiz do projeto

GET http://localhost:5022

### Listar todas as plantas

GET http://localhost:5022/api/plantas/listar

### Buscar uma planta pelo id

GET http://localhost:5022/api/plantas/buscar/1

### Deletar uma tarefa pelo id

DELETE http://localhost:5022/api/plantas/deletar/2

### Cadastrar planta

POST http://localhost:5022/api/plantas/cadastrar
Content-Type: application/json

{
    "nome": "Planta 1"
}

### Alterar planta

PUT http://localhost:5022/api/plantas/alterar/1
Content-Type: application/json

{
    "nome": "Planta nova adicionada"
}

### Cadastrar origem
POST http://localhost:5022/api/origens/cadastrar
Content-Type: application/json

{
    "pais": "Brasil"
}

### Listar todas as origens
GET http://localhost:5022/api/origens/listar

### Buscar origem pelo id
GET http://localhost:5022/api/origens/buscar/1 

### Deletar origem pelo id
DELETE http://localhost:5022/api/origens/deletar/1 

### Alterar origem
PUT http://localhost:5022/api/origens/alterar/1
Content-Type: application/json

{
    "pais": "Pais alterado"
}

### Cadastrar Tipos de plantas

POST http://localhost:5022/api/tipos/cadastrar
Content-Type: application/json

{
    "tipo": "Cacto"
}

### Listar os Tipos de Plantas 

GET http://localhost:5022/api/tipos/listar

### Buscar os tipos de Plantas

GET http://localhost:5022/api/tipos/buscar/1


### Deletar um Tipo pelo id

DELETE http://localhost:5022/api/tipos/deletar/1

### Alterar o Tipo da Planta

PUT http://localhost:5022/api/tipos/alterar/1
Content-Type: application/json

{
    "tipo": "Samambaia"
}




